name: Generate and Send Commit Graph

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      
    - name: Generate QuickChart URL
      id: chart
      run: node script.js
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ENV: ${{ runner.temp }}/env
    
    - name: Send message to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author
        custom_payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Here is the commit activity for the last two weeks",
                  "emoji": true
                }
              },
              {
                "type": "image",
                "title": {
                  "type": "plain_text",
                  "text": "Latest data",
                  "emoji": true
                },
                "block_id": "quickchart-image",
                "image_url": "${{ env.CHART_URL }}",
                "alt_text": "Chart showing latest data"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTIVITY_SLACK_WEBHOOK_URL }}
        URL: ${{ steps.chart.outputs.url }}
      if: always()
