- name: Send message to Slack
  uses: 8398a7/action-slack@v3
  with:
    status: ${{ job.status }}
    fields: repo,commit,author
    custom_payload: |
      {
        "text": "Here is the commit activity for the last two weeks",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "Here is the commit activity for the last two weeks"
            }
          },
          {
            "type": "image",
            "title": {
              "type": "plain_text",
              "text": "Latest data"
            },
            "block_id": "quickchart-image",
            "image_url": "${{ steps.chart.outputs.url }}",
            "alt_text": "Chart showing latest data"
          }
        ]
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.ACTIVITY_SLACK_WEBHOOK_URL }}
  if: always()
